language: python
python:
    - "3.4"
before_install:
    - pip install -r requirements.txt
    - pip install coveralls
install:
    - python setup.py install
script:
    coverage run --source=. setup.py test
after_success:
    coveralls
